server:
  port: 8080

spring:
  application:
    name: chat-application

  # 数据库配置 (H2)
#    datasource:
#      url: jdbc:h2:mem:chatdb
#      driver-class-name: org.h2.Driver
#      username: sa
#      password:

   #如果使用MySQL，替换为以下配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/chatdb?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
  # Neo4j 配置

  neo4j:
    uri: bolt://47.111.10.220:7687 # 你的 Neo4j 实例地址
    username: neo4j # 你的 Neo4j 用户名
    password: 619619 # 你的 Neo4j 密码
    database: neo4j

# Graphiti配置
graphiti:
  api:
  url: https://your-graphiti-cloud-api.com
  key: your-graphiti-api-key

logging:
  level:
    com.chat: DEBUG
    org.springframework.web: DEBUG

ai:
  api:
    url: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
    key: sk-02ec84237b354011bbbb41b0ccde6e05
